### ISSUE TITLE
General feedback and bugs

### ISSUE THREAD

**Issue by glitchdetector** [DoJoMan18/FiveM_Elevators#1]
You mentioned this was your first script that you released on the FiveM forums! That's cool!
A really neat and simple concept!
From the code I can assume existing releases and code has been a good inspiration, and since you're claiming it's your first, I figured I'd give you some general feedback!

# Bugs
If you go up an elevator to the top floor, you can still press UP and get sent to the same floor again.
It basically does not prevent you from trying to go up, since the `floorUp` value is still set to the top floor (rather than not set at all)
The same is true for going down from the bottom floor (after going _to_ the bottom floor)
You should keep these values locally set, rather than store them globally.
https://github.com/DoJoMan18/FiveM_Elevators/blob/402756d97d3d366fcd7ba624f6fb1a5920ce3df2/Elevator/client.lua#L71-L84

# Feedback

## GetPlayerPed(-1)
`PlayerPedId()` is favorable over `GetPlayerPed(-1)` as far as I'm aware, probably due to performance reason
https://github.com/DoJoMan18/FiveM_Elevators/blob/402756d97d3d366fcd7ba624f6fb1a5920ce3df2/Elevator/client.lua#L52

## Re-fetching stored data
You've already stored the players ped, yet still you get it again to freeze/unfreeze the player
https://github.com/DoJoMan18/FiveM_Elevators/blob/cd8467216115a334f3e4bec02c49d6d3d088ec28/Elevator/client.lua#L91
https://github.com/DoJoMan18/FiveM_Elevators/blob/cd8467216115a334f3e4bec02c49d6d3d088ec28/Elevator/client.lua#L104
https://github.com/DoJoMan18/FiveM_Elevators/blob/cd8467216115a334f3e4bec02c49d6d3d088ec28/Elevator/client.lua#L134

## Using performance heavy code
`GetDistanceBetweenCoords` is a simple to use native, but it's a slow native, being called lots of time per frame can cause a big performance issue.
You can easily get the distance between two coordinates (in vector form) with a simple set of math.
`local distance = #(pos1 - pos2)`, which you can read about [here](https://github.com/glitchdetector/fivem-how2-n-tips/blob/master/lua/get-distance-between-coords.md)!
https://github.com/DoJoMan18/FiveM_Elevators/blob/cd8467216115a334f3e4bec02c49d6d3d088ec28/Elevator/client.lua#L64

**Comment by ResqDiver1317** [comment]
I looked at your PR and I think it would be a great upgrade to this resource. Hopefully he implements your changes!

**Comment by DoJoMan18** [comment]
Thank you for your very detailed feedback!

I have merged you PR with the master branch.
